### PR TITLE
Wip lifecycle

### PR DESCRIPTION
**Pull request by mmzeeman**
- Added lifecycle handling/publishing to a topic.

See: https://developers.google.com/web/updates/2018/07/page-lifecycle-api#developer-recommendations-for-each-state

### CODE REVIEW

**Comment by mmzeeman** [comment]
This are the page lifecycle states.

Screenshot 2021-06-24 at 10 58 24

**Comment by mmzeeman** [comment]
During documenting I realise that the state transition from frozen directly to active or passive is not ideal. Therefor I want to change the state transitions to this:

graphviz

**Review by mworrell — APPROVED** [review]

**Comment by mworrell** [comment]
Good addition, will be great for the MQTT connection and the poll in the Auth worker.

**Comment by mmzeeman** [comment]
Also for the ui model. It can stop doing ui updates when the page is hidden. When it goes back to passive it can simply update everything.

Also needed for the teleview implementation we are working on. It is not needed to keep the view up to date when nobody is looking.

**Comment by mworrell** [comment]
Unsubscribing the ui-updater is great.  Then we use less power in the background.

**Pull request merged**
